#!/bin/bash
# Simple TUI game generated by ChatGPT

tput civis
x=10; y=5
while true; do
  clear
  tput cup $y $x; echo "@"
  tput cup 20 0; echo "[WASD or Arrows] Move | Ctrl+C to Exit"
  IFS= read -rsn1 input
  [[ $input == $'\e' ]] && { IFS= read -rsn2 k; input+=$k; }
  [[ $input == a || $input == $'\e[D' ]] && ((x--))
  [[ $input == d || $input == $'\e[C' ]] && ((x++))
  [[ $input == w || $input == $'\e[A' ]] && ((y--))
  [[ $input == s || $input == $'\e[B' ]] && ((y++))
done

